---
name: Changelog Checker

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened

jobs:
  changelog-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: label-checker
        with:
          script: |
            const response = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const labels = new Set(response.data.map(label => label.name))
            console.log(`Found labels: ${labels}`);

            if (labels.has("skip-changelog-checker")) {
              return "skip";
            }

      - uses: pajlads/changelog-checker@master
        if: steps.label-checker.outputs.result != 'skip'
