name: Post clang-tidy review comments

on:
  workflow_run:
    workflows: ["clang-tidy-review"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: console.log(context)

    - uses: pajlada/test-github-action/post_comments@master
