name: clang-tidy-review

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    outputs:
      test: ${{ steps.review.outputs.test }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: pajlada/test-github-action@master
      id: review
