name: clang-tidy-review

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: pajlada/test-github-action@master
      id: review
      with:
        post_comments: false

    - uses: actions/upload-artifact@v3
      with:
        name: clang-tidy-review
        path: clang_tidy_review.yaml
