name: clang-tidy-review

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-ubuntu-docker:
    name: "Build TEST DOCKER IMAGE"
    runs-on: ubuntu-latest
    container: ghcr.io/chatterino/chatterino2-build-ubuntu-20.04:latest
    strategy:
      matrix:
        include:
          # Ubuntu 20.04, Qt 5.12
          - os: ubuntu-20.04
            qt-version: 6.6.1
            force-lto: false
            plugins: false
            skip-artifact: false
            skip-crashpad: false
    env:
      C2_ENABLE_LTO: ${{ matrix.force-lto }}

    steps:
      - name: Enable plugin support
        if: matrix.plugins
        run: |
          echo "C2_PLUGINS=ON" >> "$GITHUB_ENV"
        shell: bash
